### PR TITLE
Update apt.yml

### PR DESCRIPTION
**Pull request by Swizz**

### CODE REVIEW

**Comment by Swizz** [comment]
:warning: This PR has reached its extended voting window, but it does not have a positive meritocracy review.

Please review: @eukaryote31 @muchzer @xyproto @plasmapower @rudehn @chaosbot @md678685 @swizz @amoffat @ad-m @hongaar

**Comment by Swizz** [comment]
:no_entry: PR rejected with a vote of 1 for and 0 against, a weighted total of 1.0 and a threshold of 1.0, and **NO** current meritocracy review.

Open a new PR to restart voting.

**Comment by PlasmaPower** [comment]
Maybe we should disable this for dev environments...

**Comment by Swizz** [comment]
Ow. Sorry :x

**Comment by PlasmaPower** [comment]
No problem :)

**Pull request closed without merging**
